# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
env:
   variables:
     PROJECT: AWS_Lab4
     DOTNET_CORE_RUNTIME: 3.1

phases:   
  install:
    runtime-versions:
      dotnet: ${DOTNET_CORE_RUNTIME}
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore
      
  build:
    commands:
      - echo Build started on 'date'
      - dotnet build -c Release
      - dotnet test -c Release --logger trx --results-directory testresults
      
  post_build:
    commands:
      - echo Publish started on `date`
      - touch test_report.xml

reports:
  ${PROJECT}:
    file-format: VisualStudioTrx
    files:
      - test_report.xml

artifacts:
  files:
    - '**/*'

